---
powerButton:
    topic: dst/motor/cutter/powerOn
    values: [true,false]
    label: Power
rpmSlider:
    topic: dst/motor/drive/speed
    values: [0,20000]
rpmChart:
    topics: ["src/triac/triac/rpmTarget","src/triac/triac/rpmMeasured"]
    values: [0,20000]
    samples: 1000

mqttConnectionText:
    label: "MQTT Connection URL"
dashboard:
    row: [ powerButton, rpmSlider ]
    row: [ rpmChart ]
...
